version: "3"

x-config:
  build_context: &default-build_context ci
  build_args_image: &default-build_args_image
    ENV_BASIC_IMAGE: alpine
    ENV_BASIC_IMAGE_TAG: 3.19
  build_args_nodejs: &default-build_args_nodejs
    ENV_BASIC_IMAGE: node
    ENV_BASIC_IMAGE_TAG: lts-alpine3.19
  working_dir: &default-working_dir /root/workbench
  volumes: &default-volume
    - .:/root/workbench

services:
  eclint:
    build:
      context: *default-build_context
      dockerfile: pod/lint/eclint/Dockerfile
      args: *default-build_args_nodejs
    working_dir: *default-working_dir
    command:
      - eclint
      - check
    volumes: *default-volume

  spellcheck:
    build:
      context: *default-build_context
      dockerfile: pod/lint/spellcheck/Dockerfile
      args: *default-build_args_image
    working_dir: *default-working_dir
    command:
      - /bin/sh
      - -c
      - git grep --cached -l '' | xargs codespell --ignore-words=.ignore_words
    volumes: *default-volume
