name: CI-Lint

on:
  push:
    branches:
      - 'master'
      - 'release/**'
  pull_request:
    branches:
      - 'master'

jobs:
  eclint:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-20.04
        os_name:
          - linux

    runs-on: ${{ matrix.platform }}
    env:
      SERVER_NAME: ${{ matrix.os_name }}

    steps:
      - name: System install basic env
        run: |
          sudo apt update && sudo apt install neofetch

      - name: System print info
        run: |
          neofetch --stdout

      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Eclint check
        run: |
          make _lint_eclint

      - name: Setup tmate session
        if: ${{ contains(github.event.pull_request.labels.*.name, 'ci-debug') && always() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 45
